<Project>
  <PropertyGroup>
    <DebugType>portable</DebugType>
    <LangVersion>11</LangVersion>

    <VersionPrefix>3.4.0</VersionPrefix>
    <Authors>chris mckee,hotchkj</Authors>
    <TargetFrameworks>netstandard2.0;netstandard2.1;net10.0</TargetFrameworks>
    <OutputType>Library</OutputType>
    <PackageProjectUrl>https://github.com/chrismckee/AspNet.DataProtection.Aws</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/chrismckee/AspNet.DataProtection.Aws</RepositoryUrl>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <!-- Disable analyzer warning since AWS SDK has incorrect versioning behaviour -->
    <!-- 1701;1702;1705 are Microsoft advice - cargo culting -->
    <NoWarn>1701;1702;1705;IDE1002</NoWarn>
    <DebugSymbols>true</DebugSymbols>

    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\aspnetdpa.snk</AssemblyOriginatorKeyFile>
    <PublicKey>377e010700f04e36</PublicKey>
    <PublicSign Condition="'$(OS)' != 'Windows_NT'">true</PublicSign>

    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <IncludeSource>true</IncludeSource>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <Deterministic>true</Deterministic>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    <!-- https://aka.ms/vs-build-acceleration -->
    <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>

    <RepositoryType>c#</RepositoryType>
    <PackageIcon>logo.png</PackageIcon>
    <PackageIconUrl/>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <!-- Analyzers -->
  <PropertyGroup>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest</AnalysisLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all"/>
  </ItemGroup>

  <ItemGroup>
    <None Include="../../logo.png" Pack="true" Visible="false" PackagePath=""/>
    <None Include="../../LICENSE.md" Pack="true" Visible="false" PackagePath=""/>
    <None Include="../../README.md" Pack="true" Visible="false" PackagePath=""/>
  </ItemGroup>

  <!-- Release configuration
       Enable sbom generation -->
  <Choose>
    <When Condition="'$(Configuration)' == 'Release'">
      <PropertyGroup>
        <GenerateSBOM>true</GenerateSBOM>
      </PropertyGroup>
      <ItemGroup>
        <PackageReference Include="Microsoft.Sbom.Targets" PrivateAssets="All"/>
      </ItemGroup>
    </When>
  </Choose>
</Project>
